=== DougStirling/CAST/core/structure/bookXmlDefn.dtd
<!ATTLIST book name CDATA #REQUIRED>
<!ATTLIST book tocTitle CDATA #REQUIRED>
<!ATTLIST book versionImage CDATA #REQUIRED>
<!ATTLIST book logoGif CDATA #IMPLIED>
<!ATTLIST book language CDATA #REQUIRED>
<!ATTLIST book type CDATA #REQUIRED>
<!ATTLIST book summaryPdfUrl CDATA #IMPLIED>

<!ELEMENT book (description? , (chapter | part)*)>

<!ELEMENT description (#PCDATA)>

<!ATTLIST chapter dir CDATA #REQUIRED>
<!ATTLIST chapter file CDATA #REQUIRED>

<!ELEMENT chapter ((section | page)*)>

<!ATTLIST section dir CDATA #REQUIRED>
<!ATTLIST section file CDATA #REQUIRED>

<!ELEMENT section EMPTY>

<!ATTLIST page dir CDATA #REQUIRED>
<!ATTLIST page file CDATA #REQUIRED>

<!ELEMENT page EMPTY>

<!ELEMENT part EMPTY>
<!ATTLIST part name CDATA #REQUIRED>

=== DougStirling/CAST/core/bk/idems_prob/xml/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "../../../structure/bookXmlDefn.dtd">
<book language="en" name="Introduction to Probability book" tocTitle="Introduction to Probability book" type="book_s_v" versionImage="images/castTheory">
<description>idems#This e-book introduces some of the probability theory that underlies statisticals.</description>

<chapter dir="bk/general" file="ch_preface">
	<section dir="bk/general" file="sec_aboutCast"/>
	<section dir="bk/general" file="sec_otherInfo"/>
</chapter>


<chapter dir="bk/mathStats" file="ch_probability">
<section dir="bk/mathStats" file="sec_probDefinitions"/>
<section dir="bk/mathStats" file="sec_probRules"/>
<section dir="bk/mathStats" file="sec_probCondit"/>




</chapter>

<chapter dir="bk/mathStats" file="ch_distributions">
<section dir="bk/mathStats" file="sec_discreteDistns"/>

<section dir="bk/mathStats" file="sec_continuousDistns"/>
<section dir="bk/mathStats" file="sec_randomSample"/>
<section dir="bk/mathStats" file="sec_uniform"/>

</chapter>
<chapter dir="bk/mathStats" file="ch_bernoulliTrials">
<section dir="bk/mathStats" file="sec_bernoulli"/>
<section dir="bk/mathStats" file="sec_binomial"/>
<section dir="bk/mathStats" file="sec_geometric"/>
<section dir="bk/mathStats" file="sec_negBinomial"/>
</chapter>



<chapter dir="bk/mathStats" file="ch_continuous">
<section dir="bk/mathStats" file="sec_continuousProbs"/>
<section dir="bk/mathStats" file="sec_continuousMeanVar"/>
<section dir="bk/mathStats" file="sec_continuousSamples"/>

<section dir="bk/idems_prob" file="sec_normal"/>
</chapter>

<chapter dir="bk/mathStats" file="ch_eventsInTime">
<section dir="bk/mathStats" file="sec_poisson"/>
<section dir="bk/mathStats" file="sec_exponential"/>

<section dir="bk/idems_prob" file="sec_erlang"/>
</chapter>









<chapter dir="bk/idems_prob" file="ch_sampling">
	<section dir="bk/exercises" file="sec_probDistn"/>
	<section dir="bk/exercises" file="sec_normalDistn"/>
	<section dir="bk/exercises" file="sec_binomial"/>
	<section dir="bk/exercises" file="sec_meanSum"/>
</chapter>
</book>

=== DougStirling/CAST/core/bk/businessx/xml/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "../../../structure/bookXmlDefn.dtd">
<book language="en" name="Business Lecturer Version" tocTitle="Business Lecturer Version" type="lecture" versionImage="../business/images/castBusiness">
<description>core#This e-book is closely related to the introductory business e-book for students. Its applets are larger and it contains minimal descriptive text, making it easier to use in lectures.</description>

<chapter dir="bk/general" file="ch_preface">
	<section dir="bk/generalx" file="sec_aboutCast"/>
	<section dir="bk/generalx" file="sec_otherInfo"/>
</chapter>

<chapter dir="bk/generalx" file="ch_intro">
	<section dir="bk/businessx" file="sec_structures"/>
	<section dir="bk/businessx" file="sec_variation"/>
</chapter>

<chapter dir="bk/generalx" file="ch_univar">
	<section dir="bk/businessx" file="sec_valueDisplay"/>
	<section dir="bk/generalx" file="sec_displayInterp"/>
	<section dir="bk/businessx" file="sec_density"/>
	<section dir="bk/generalx" file="sec_boxPlot"/>
	<section dir="bk/businessx" file="sec_centerSpread"/>
	<section dir="bk/generalx" file="sec_moreVariation"/>
	<section dir="bk/generalx" file="sec_percentile"/>
	<section dir="bk/businessx" file="sec_transform"/>
	<section dir="bk/businessx" file="sec_counts"/>
</chapter>

<chapter dir="bk/generalx" file="ch_bivar">
	<section dir="bk/businessx" file="sec_scatterplot"/>
	<section dir="bk/businessx" file="sec_relationship"/>
	<section dir="bk/businessx" file="sec_correlation"/>
	<section dir="bk/businessx" file="sec_leastSqrs"/>
	<section dir="bk/businessx" file="sec_curvature"/>
</chapter>

<chapter dir="bk/generalx" file="ch_timeSeries">
	<section dir="bk/businessx" file="sec_timePlot"/>
	<section dir="bk/generalx" file="sec_smoothing"/>
	<section dir="bk/generalx" file="sec_trend"/>
	<section dir="bk/generalx" file="sec_cyclic"/>
	<section dir="bk/generalx" file="sec_seasonal"/>
	<section dir="bk/generalx" file="sec_multiplicative"/>
</chapter>

<chapter dir="bk/generalx" file="ch_cat">
	<section dir="bk/businessx" file="sec_freqTable"/>
	<section dir="bk/businessx" file="sec_univarCat"/>
	<section dir="bk/businessx" file="sec_groupedCat"/>
	<section dir="bk/generalx" file="sec_bivarCat"/>
	<section dir="bk/businessx" file="sec_tableDisplay"/>
	<section dir="bk/businessx" file="sec_logistic"/>
</chapter>

<chapter dir="bk/generalx" file="ch_multivar">
	<section dir="bk/businessx" file="sec_multivariate"/>
	<section dir="bk/businessx" file="sec_regnGroups"/>
	<section dir="bk/generalx" file="sec_multiRegn"/>
	<section dir="bk/businessx" file="sec_lurking"/>
</chapter>

<chapter dir="bk/generalx" file="ch_sample">
	<section dir="bk/businessx" file="sec_popSamp"/>
	<section dir="bk/businessx" file="sec_infPopn"/>
	<section dir="bk/businessx" file="sec_probDensity"/>
	<section dir="bk/businessx" file="sec_probSim"/>
	<section dir="bk/businessx" file="sec_randomMean"/>
	<section dir="bk/businessx" file="sec_normalDistn"/>
	<section dir="bk/businessx" file="sec_randomPropn"/>
	<section dir="bk/generalx" file="sec_sampPractice"/>
	<section dir="bk/generalx" file="sec_controlChart"/>
</chapter>

<chapter dir="bk/businessx" file="ch_expDesign">
	<section dir="bk/businessx" file="sec_causal"/>
	<section dir="bk/businessx" file="sec_designIntro"/>
</chapter>

<chapter dir="bk/generalx" file="ch_estimation">
	<section dir="bk/businessx" file="sec_estIntro"/>
	<section dir="bk/businessx" file="sec_seMean"/>
	<section dir="bk/businessx" file="sec_ciMean"/>
	<section dir="bk/businessx" file="sec_estPropn"/>
	<section dir="bk/businessx" file="sec_ciExtra"/>
	<section dir="bk/businessx" file="sec_estOther"/>
</chapter>

<chapter dir="bk/generalx" file="ch_testing">
	<section dir="bk/businessx" file="sec_testIntro"/>
	<section dir="bk/businessx" file="sec_testPropn"/>
	<section dir="bk/businessx" file="sec_testMean"/>
	<section dir="bk/generalx" file="sec_decision"/>
	<section dir="bk/businessx" file="sec_testPValue"/>
</chapter>

<chapter dir="bk/generalx" file="ch_twoGroups">
	<section dir="bk/businessx" file="sec_twoGroupModel"/>
	<section dir="bk/generalx" file="sec_sumDiff"/>
	<section dir="bk/businessx" file="sec_twoGroupInf"/>
	<section dir="bk/businessx" file="sec_twoGroupPropn"/>
	<section dir="bk/businessx" file="sec_testPaired"/>
	<section dir="bk/businessx" file="sec_multiGroup"/>
</chapter>

<chapter dir="bk/generalx" file="ch_regnInference">
	<section dir="bk/businessx" file="sec_regnModel"/>
	<section dir="bk/businessx" file="sec_regnEst"/>
	<section dir="bk/businessx" file="sec_regnTest"/>
	<section dir="bk/businessx" file="sec_regnPred"/>
	<section dir="bk/businessx" file="sec_regnProblem"/>
</chapter>

<chapter dir="bk/generalx" file="ch_independence">
	<section dir="bk/businessx" file="sec_prob"/>
	<section dir="bk/businessx" file="sec_indep"/>
</chapter>



</book>

=== DougStirling/CAST/core/bk/masseyBe/xml/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "../../../structure/bookXmlDefn.dtd">
<book language="en" logoGif="logo_massey.gif" name="Massey BE Student Version" summaryPdfUrl="http://castAdmin2.massey.ac.nz/pdf/masseyBe" tocTitle="Massey BE Student Version" type="book_s" versionImage="../general/images/castGeneral">
<description>Massey University#The first part of this e-book covers material that should already be known by students at Massey University starting their BE degrees. Other parts contain material relevant to later years in their degrees.</description>

<chapter dir="bk/general" file="ch_preface">
	<section dir="bk/general" file="sec_aboutCast"/>
	<section dir="bk/general" file="sec_otherInfo"/>
</chapter>

<part name="For 100-level projects"/>
<chapter dir="bk/massey120" file="ch_intro">
	<section dir="bk/general" file="sec_context"/>
	<section dir="bk/massey120" file="sec_structures"/>
	<section dir="bk/massey120" file="sec_variation"/>
</chapter>



<chapter dir="bk/massey120" file="ch_graphicalSum">
	<section dir="bk/massey120" file="sec_valueDisplay"/>
	<section dir="bk/general" file="sec_displayInterp"/>
	<section dir="bk/massey120" file="sec_density"/>
	<section dir="bk/massey120" file="sec_counts"/>
	<section dir="bk/general" file="sec_freqTable"/>
	<section dir="bk/massey120" file="sec_univarCat"/>
</chapter>
	
<chapter dir="bk/massey120" file="ch_sumStats">
	<section dir="bk/massey120" file="sec_boxPlot"/>
	<section dir="bk/massey120" file="sec_centerSpread"/>
</chapter>
	
<chapter dir="bk/massey120" file="ch_bivar">
	<section dir="bk/general" file="sec_scatterplot"/>
	<section dir="bk/general" file="sec_relationship"/>
	<section dir="bk/massey120" file="sec_correlation"/>
	<section dir="bk/massey120" file="sec_leastSqrs"/>
	<section dir="bk/massey120" file="sec_rSquared"/>
	<section dir="bk/massey120" file="sec_continTable"/>
</chapter>





<chapter dir="bk/massey120" file="ch_basicCollection">
	<section dir="bk/general" file="sec_causal"/>
	<section dir="bk/massey120" file="sec_sampPractice"/>
	<section dir="bk/massey120" file="sec_designIntro"/>
</chapter>



<part name="For 200-level projects"/>
<chapter dir="bk/massey120" file="ch_sample">
	<section dir="bk/massey120" file="sec_popSamp"/>
	<section dir="bk/massey120" file="sec_infPopn"/>
	<section dir="bk/massey120" file="sec_probDensity"/>
	<section dir="bk/massey120" file="sec_probTable"/>
	<section dir="bk/massey120" file="sec_probSim"/>
</chapter>
<chapter dir="bk/massey120" file="ch_meanPropnDistn">
	<section dir="bk/massey120" file="sec_randomMean"/>
	<section dir="bk/massey120" file="sec_normalDistn"/>
	<section dir="bk/general" file="sec_randomPropn"/>
</chapter>





<chapter dir="bk/massey120" file="ch_masteryTests">
	<section dir="bk/massey120" file="sec_masteryOne"/>
	<section dir="bk/massey120" file="sec_masteryTwo"/>
	<section dir="bk/massey120" file="sec_masteryThree"/>
</chapter>
<part name="Slightly more advanced"/>
	
<chapter dir="bk/massey120" file="ch_timeSeries">
	<section dir="bk/general" file="sec_timePlot"/>
	<section dir="bk/massey120" file="sec_smoothing"/>
	<section dir="bk/general" file="sec_trend"/>
</chapter>
<chapter dir="bk/massey120" file="ch_moreGraphics">
	<section dir="bk/massey120" file="sec_moreGraphs"/>
	<section dir="bk/massey120" file="sec_transform"/>
	<section dir="bk/massey120" file="sec_nonlinear"/>
	<section dir="bk/general" file="sec_multivariate"/>
</chapter>

<chapter dir="bk/massey120" file="ch_dataPresentation">
	<section dir="bk/official" file="sec_tableDisplay"/>
	<section dir="bk/massey120" file="sec_barPieDisplay"/>
	<section dir="bk/massey120" file="sec_groupGraph"/>
	<section dir="bk/massey120" file="sec_otherGraphs"/>
	<section dir="bk/massey120" file="sec_graphs"/>
</chapter>

<chapter dir="bk/massey120" file="ch_moreCollection">
	<section dir="bk/massey120" file="sec_lurking"/>
	<section dir="bk/massey120" file="sec_samplingSchemes"/>
	<section dir="bk/massey120" file="sec_blocks"/>
</chapter>

<chapter dir="bk/massey120" file="ch_estimation">
	<section dir="bk/general" file="sec_estIntro"/>
	<section dir="bk/massey120" file="sec_seMean"/>
	<section dir="bk/general" file="sec_ciMean"/>
	<section dir="bk/general" file="sec_estPropn"/>
	<section dir="bk/general" file="sec_ciExtra"/>
</chapter>









</book>

=== DougStirling/CAST/core/bk/climatic_c4/xml/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "../../../structure/bookXmlDefn.dtd">
<book language="en" name="CAST for Climatology: More Inference" tocTitle="CAST for Climatology: More Inference" type="book_s_v" versionImage="images/castClimatic_c4">
<description>Climatology course (University of Reading)#This is the last of four e-books that accompany the four levels of a course run by the University of Reading for climatologists. It describes inference about differences between groups and relationships.</description>

<chapter dir="bk/general" file="ch_preface">
	<section dir="bk/general" file="sec_aboutCast"/>
	<section dir="bk/general" file="sec_otherInfo"/>
</chapter>

<chapter dir="bk/climatic_c4" file="ch_aboutReln">
	<section dir="bk/biometric" file="sec_causal"/>
	<section dir="bk/biometric" file="sec_lurking"/>
</chapter>

<chapter dir="bk/climatic_c4" file="ch_expDesign">
	<section dir="bk/biometric" file="sec_designIntro"/>
	<section dir="bk/biometric" file="sec_pairBlock"/>
	<section dir="bk/biometric" file="sec_designTwo"/>
	<section dir="bk/general" file="sec_designPrelim"/>
</chapter>

<chapter dir="bk/climatic_c4" file="ch_twoMeans">
	<section dir="bk/biometric" file="sec_twoGroupModel"/>
	<section dir="bk/general" file="sec_sumDiff"/>
	<section dir="bk/climatic_c4" file="sec_ciDiff"/>
	<section dir="bk/climatic_c4" file="sec_testDiff"/>
	<section dir="bk/biometric" file="sec_testPaired"/>
</chapter>

<chapter dir="bk/climatic_c4" file="ch_twoPropns">
	<section dir="bk/climatic_c4" file="sec_ciPropnDiff"/>
	<section dir="bk/climatic_c4" file="sec_testPropnDiff"/>
</chapter>

<chapter dir="bk/climatic_c4" file="ch_manyMeans">
	<section dir="bk/climatic_c4" file="sec_commonSD"/>
	<section dir="bk/climatic_c4" file="sec_ssqF"/>
	<section dir="bk/general" file="sec_randBlock"/>
</chapter>

<chapter dir="bk/climatic_c4" file="ch_regnModel">
	<section dir="bk/biometric" file="sec_regnModel"/>
	<section dir="bk/climatic_c4" file="sec_regnEst"/>
</chapter>

<chapter dir="bk/climatic_c4" file="ch_regnInf">
	
	<section dir="bk/general" file="sec_regnTest"/>
	<section dir="bk/biometric" file="sec_regnPred"/>
</chapter>

<chapter dir="bk/climatic_c4" file="ch_advRegn">
	<section dir="bk/biometric" file="sec_regnProblem"/>
	<section dir="bk/biometric" file="sec_logistic"/>
</chapter>

<chapter dir="bk/general" file="ch_independence">
	<section dir="bk/climatic_c4" file="sec_prob"/>
	<section dir="bk/climatic_c4" file="sec_indep"/>
	<section dir="bk/climatic_c4" file="sec_testIndep"/>
</chapter>



</book>

=== DougStirling/CAST/core/bk/african_c1/xml/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "../../../structure/bookXmlDefn.dtd">
<book language="en" name="CAST for Africa: Exploring Data" tocTitle="CAST for Africa: Exploring Data" type="book_s_v" versionImage="images/castAfrica_c1">
<description>African e-books#This is the first of two customised e-books whose content was chosen to match typical first courses in Statistics in Africa and some of whose data sets and scenarios have been changed to African ones. The first e-book concentrates on methods to graphically and numerically summarise data.</description>

<chapter dir="bk/general" file="ch_preface">
	<section dir="bk/general" file="sec_aboutCast"/>
	<section dir="bk/general" file="sec_otherInfo"/>
</chapter>

<chapter dir="bk/african_c1" file="ch_intro">
	<section dir="bk/biometric" file="sec_context"/>
	<section dir="bk/african_c1" file="sec_structures"/>
	<section dir="bk/african_c1" file="sec_variation"/>
</chapter>

<chapter dir="bk/african_c1" file="ch_displayData">
	<section dir="bk/african_c1" file="sec_dotPlot"/>
	<section dir="bk/african_c1" file="sec_stemLeaf"/>
	<section dir="bk/african_c1" file="sec_displayInterp"/>
</chapter>

<chapter dir="bk/african_c1" file="ch_graphSumm">
	<section dir="bk/african_c1" file="sec_density"/>
	<section dir="bk/african_c1" file="sec_boxPlot"/>
	<section dir="bk/african_c1" file="sec_counts"/>
</chapter>

<chapter dir="bk/african_c1" file="ch_numSumm">
	<section dir="bk/african_c1" file="sec_center"/>
	<section dir="bk/african_c1" file="sec_spread"/>
	<section dir="bk/african_c1" file="sec_varAndGroups"/>
	<section dir="bk/african_c1" file="sec_moreVariation"/>
</chapter>

<chapter dir="bk/african_c1" file="ch_percentiles">
	<section dir="bk/african_c1" file="sec_propn"/>
	<section dir="bk/african_c1" file="sec_percentile"/>
</chapter>

<chapter dir="bk/general" file="ch_cat">
	<section dir="bk/african_c1" file="sec_freqTable"/>
	<section dir="bk/african_c1" file="sec_bar"/>
	<section dir="bk/african_c1" file="sec_pie"/>
	<section dir="bk/biometric" file="sec_groupedCat"/>
	<section dir="bk/general" file="sec_tableDisplay"/>
</chapter>

<chapter dir="bk/african_c1" file="ch_relns">
	<section dir="bk/biometric" file="sec_scatterplot"/>
	<section dir="bk/general" file="sec_relationship"/>
	<section dir="bk/general" file="sec_bivarCat"/>
</chapter>

<chapter dir="bk/african_c1" file="ch_sumReln">
	<section dir="bk/biometric" file="sec_correlation"/>
	<section dir="bk/african_c1" file="sec_leastSqrs"/>
	<section dir="bk/african_c1" file="sec_simpleDiag"/>
</chapter>

<chapter dir="bk/african_c1" file="ch_transform">
	<section dir="bk/biometric" file="sec_transform"/>
	<section dir="bk/general" file="sec_curvature"/>
</chapter>

<chapter dir="bk/african_c1" file="ch_multivar">
	<section dir="bk/african_c1" file="sec_regnGroups"/>
	<section dir="bk/african_c1" file="sec_thirdVar"/>
	<section dir="bk/african_c1" file="sec_brushing"/>
</chapter>

<chapter dir="bk/biometric" file="ch_timeSeries">
	<section dir="bk/biometric" file="sec_timePlot"/>
	<section dir="bk/general" file="sec_smoothing"/>
	<section dir="bk/general" file="sec_trend"/>
</chapter>


</book>

=== DougStirling/CAST/core/bk/climatic_c2/xml/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "../../../structure/bookXmlDefn.dtd">
<book language="en" name="CAST for Africa: Inference" tocTitle="CAST for Africa: Inference" type="book_s_v" versionImage="images/castClimatic_c2">
<description>Climatology course (University of Reading)#This is the second of four e-books that accompany the four levels of a course run by the University of Reading for climatologists. It introduces the ideas of random samples, confidence intervals and hypothesis tests.</description>

<chapter dir="bk/general" file="ch_preface">
	<section dir="bk/general" file="sec_aboutCast"/>
	<section dir="bk/general" file="sec_otherInfo"/>
</chapter>

<chapter dir="bk/climatic_c2" file="ch_modelVar">
	<section dir="bk/climatic_c2" file="sec_modelIntro"/>
	<section dir="bk/climatic_c2" file="sec_popSamp"/>
	<section dir="bk/biometric" file="sec_infPopn"/>
	<section dir="bk/biometric" file="sec_probDensity"/>
	<section dir="bk/biometric" file="sec_probSim"/>
</chapter>

<chapter dir="bk/climatic_c2" file="ch_sampDistn">
	<section dir="bk/biometric" file="sec_randomMean"/>
	<section dir="bk/biometric" file="sec_normalDistn"/>
	<section dir="bk/biometric" file="sec_randomPropn"/>
</chapter>

<chapter dir="bk/climatic_c2" file="ch_estimation">
	<section dir="bk/biometric" file="sec_estIntro"/>
	<section dir="bk/general" file="sec_seMean"/>
	<section dir="bk/climatic_c2" file="sec_sePropn"/>
</chapter>

<chapter dir="bk/climatic_c2" file="ch_cis">
	<section dir="bk/climatic_c2" file="sec_ciMean"/>
	<section dir="bk/climatic_c2" file="sec_ciPropn"/>
</chapter>

<chapter dir="bk/climatic_c2" file="ch_sampSurv">
	<section dir="bk/climatic_c2" file="sec_sampSchemes"/>
	<section dir="bk/climatic_c2" file="sec_sampErr"/>
	<section dir="bk/climatic_c2" file="sec_survey"/>
	<section dir="bk/climatic_c2" file="sec_sampSize"/>
</chapter>

<chapter dir="bk/climatic_c2" file="ch_testProp">
	<section dir="bk/biometric" file="sec_testIntro"/>
	<section dir="bk/biometric" file="sec_testPropn"/>
</chapter>

<chapter dir="bk/climatic_c2" file="ch_testMean">
	<section dir="bk/biometric" file="sec_testMean"/>
	<section dir="bk/biometric" file="sec_testPValue"/>
</chapter>



</book>

=== DougStirling/CAST/core/bk/massey100/xml/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "../../../structure/bookXmlDefn.dtd">
<book language="en" logoGif="logo_massey.gif" name="Massey 100 Student Version" tocTitle="Massey 100 Student Version" type="book_s" versionImage="../general/images/castGeneral">
<description>Massey University (old)#This is an e-book that was customised to match the content of the Massey University paper 161.100. (The paper is no longer taught.)</description>

<chapter dir="bk/general" file="ch_preface">
	<section dir="bk/general" file="sec_aboutCast"/>
	<section dir="bk/general" file="sec_otherInfo"/>
</chapter>

<chapter dir="bk/massey100" file="ch_dataDistns">
	<section dir="bk/general" file="sec_context"/>
	<section dir="bk/massey100" file="sec_structures"/>
	<section dir="bk/general" file="sec_variation"/>
	<section dir="bk/massey100" file="sec_valueDisplay"/>
	<section dir="bk/massey100" file="sec_density"/>
	<section dir="bk/massey100" file="sec_counts"/>
	<section dir="bk/massey100" file="sec_univarCat"/>
	<section dir="bk/massey100" file="sec_normalDistn"/>
</chapter>

<chapter dir="bk/massey100" file="ch_numSummaries">
	<section dir="bk/massey100" file="sec_boxPlot"/>
	<section dir="bk/general" file="sec_centerSpread"/>
	<section dir="bk/massey100" file="sec_countSummary"/>
</chapter>

<chapter dir="bk/massey100" file="ch_bivar">
	<section dir="bk/general" file="sec_scatterplot"/>
	<section dir="bk/general" file="sec_relationship"/>
	<section dir="bk/general" file="sec_correlation"/>
	<section dir="bk/general" file="sec_leastSqrs"/>
	<section dir="bk/general" file="sec_curvature"/>
</chapter>

<chapter dir="bk/massey100" file="ch_dataCollect">
	<section dir="bk/general" file="sec_popSamp"/>
	<section dir="bk/general" file="sec_infPopn"/>
	<section dir="bk/general" file="sec_probDensity"/>
	<section dir="bk/general" file="sec_sampPractice"/>
	<section dir="bk/general" file="sec_causal"/>
	<section dir="bk/general" file="sec_designIntro"/>
	<section dir="bk/general" file="sec_designPrelim"/>
</chapter>

<chapter dir="bk/massey100" file="ch_probSamp">
	<section dir="bk/massey100" file="sec_probDensity"/>
	<section dir="bk/general" file="sec_groupedCat"/>
	<section dir="bk/general" file="sec_bivarCat"/>
	<section dir="bk/general" file="sec_prob"/>
	<section dir="bk/general" file="sec_randomMean"/>
	<section dir="bk/general" file="sec_randomPropn"/>
</chapter>

<chapter dir="bk/massey100" file="ch_quality">
	<section dir="bk/general" file="sec_controlChart"/>
</chapter>

<chapter dir="bk/massey100" file="ch_est">
	<section dir="bk/general" file="sec_estIntro"/>
	<section dir="bk/general" file="sec_seMean"/>
	<section dir="bk/general" file="sec_ciMean"/>
	<section dir="bk/general" file="sec_estPropn"/>
	<section dir="bk/general" file="sec_ciExtra"/>
	<section dir="bk/general" file="sec_twoGroupModel"/>
	<section dir="bk/massey100" file="sec_twoGroupCi"/>
	<section dir="bk/massey100" file="sec_twoGroupPropnCi"/>
	<section dir="bk/massey100" file="sec_pairedCi"/>
</chapter>

<chapter dir="bk/massey100" file="ch_test">
	<section dir="bk/general" file="sec_testIntro"/>
	<section dir="bk/general" file="sec_testPropn"/>
	<section dir="bk/general" file="sec_testMean"/>
	<section dir="bk/massey100" file="sec_twoGroupTest"/>
	<section dir="bk/massey100" file="sec_twoGroupPropnTest"/>
	<section dir="bk/massey100" file="sec_pairedTest"/>
</chapter>

<chapter dir="bk/massey100" file="ch_anova">
	<section dir="bk/massey100" file="sec_multiGroup"/>
	<section dir="bk/massey100" file="sec_randBlock"/>
</chapter>

<chapter dir="bk/massey100" file="ch_expDesign">
	<section dir="bk/general" file="sec_pairBlock"/>
	<section dir="bk/general" file="sec_designTwo"/>
</chapter>

<chapter dir="bk/massey100" file="ch_regn">
	<section dir="bk/general" file="sec_regnModel"/>
	<section dir="bk/general" file="sec_regnEst"/>
	<section dir="bk/general" file="sec_regnTest"/>
	<section dir="bk/general" file="sec_regnPred"/>
	<section dir="bk/general" file="sec_regnProblem"/>
	<section dir="bk/regn" file="sec_leastSqrsTwo"/>
	<section dir="bk/regn" file="sec_regnInfTwo"/>
</chapter>

</book>

=== DougStirling/CAST/core/bk/wfp_c4/xml/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "../../../structure/bookXmlDefn.dtd">
<book language="en" logoGif="logo_wfp.gif" name="CAST for WFP: Advanced" tocTitle="CAST for WFP: Advanced" type="book_s" versionImage="images/castWfp_c4">
<description>World Food Programme#This is the last of four e-books that were written as short courses for workers in the World Food Programme. It describes more advanced statistical methods that have less relevance in the World Food Programme.</description>

<chapter dir="bk/general" file="ch_preface">
	<section dir="bk/general" file="sec_aboutCast"/>
	<section dir="bk/general" file="sec_otherInfo"/>
</chapter>

<chapter dir="bk/african_c2" file="ch_sampDistn">
	<section dir="bk/general" file="sec_normalDistn"/>
</chapter>

<chapter dir="bk/business" file="ch_timeSeries">
	<section dir="bk/general" file="sec_multiplicative"/>
</chapter>

<chapter dir="bk/general" file="ch_estimation">
	<section dir="bk/african_c2" file="sec_estOther"/>
</chapter>

<chapter dir="bk/general" file="ch_independence">
	<section dir="bk/african_c2" file="sec_prob"/>
</chapter>

<chapter dir="bk/african_c2" file="ch_aboutReln">
	<section dir="bk/biometric" file="sec_causal"/>
	<section dir="bk/biometric" file="sec_lurking"/>
</chapter>

<chapter dir="bk/african_c2" file="ch_expDesign">
	<section dir="bk/biometric" file="sec_designIntro"/>
	<section dir="bk/general" file="sec_pairBlock"/>
	<section dir="bk/biometric" file="sec_designTwo"/>
	<section dir="bk/general" file="sec_designPrelim"/>
</chapter>

<chapter dir="bk/african_c2" file="ch_manyMeans">
	<section dir="bk/general" file="sec_randBlock"/>
</chapter>

<chapter dir="bk/regn" file="ch_simpleRegn">
	<section dir="bk/regn" file="sec_diagnostics"/>
	<section dir="bk/general" file="sec_logistic"/>
</chapter>

<chapter dir="bk/regn" file="ch_multipleRegn">
	<section dir="bk/regn" file="sec_glm"/>
	<section dir="bk/regn" file="sec_nonlinTwo"/>
	<section dir="bk/regn" file="sec_interact"/>
	<section dir="bk/regn" file="sec_diagnosticsTwo"/>
</chapter>

<chapter dir="bk/regn" file="ch_regnAnova">
	<section dir="bk/regn" file="sec_regnAnova"/>
	<section dir="bk/regn" file="sec_multiRegnAnova"/>
	<section dir="bk/regn" file="sec_multicollin"/>
	<section dir="bk/regn" file="sec_seqRegnSsq"/>
	<section dir="bk/regn" file="sec_nonlinAnova"/>
	<section dir="bk/regn" file="sec_glmAnova"/>
</chapter>



</book>
