=== DougStirling/CAST/core/structure/sectionXmlDefn.dtd
<!ATTLIST section name CDATA #REQUIRED>
<!ATTLIST section shortName CDATA #IMPLIED>
<!ELEMENT section (topText?, page*)>

<!ELEMENT topText (#PCDATA)>

<!ATTLIST page dir CDATA #REQUIRED>
<!ATTLIST page filePrefix CDATA #REQUIRED>
<!ATTLIST page summaryDir CDATA #IMPLIED>
<!ATTLIST page summaryFilePrefix CDATA #IMPLIED>
<!ATTLIST page videoDir CDATA #IMPLIED>
<!ATTLIST page videoFilePrefix CDATA #IMPLIED>
<!ATTLIST page note CDATA #IMPLIED>				<!-- Comment after page name in section list -->
<!ATTLIST page nameOverride CDATA #IMPLIED>		<!-- Overrides page name -->
<!ELEMENT page (#PCDATA)>

=== DougStirling/CAST/core/bk/agExper/xml/sec_contrasts.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE section SYSTEM "../../../structure/sectionXmlDefn.dtd">

<section name='Contrasts and constraints'>


<page dir='en/contrasts' filePrefix='contrasts1'>The combinations of factor levels used are called treatments. The sum of squares explained by the treatments (treated as a single factor) is closely related to those of the main effects and interaction between the actual factors.</page>
<page dir='en/contrasts' filePrefix='contrasts2'>The model with no interaction between two factors can be expressed with constraints on the parameters of the most general model. Similarly, models without main effects can be expressed in terms of constraints.</page>
<page dir='en/contrasts' filePrefix='contrasts3'>Models where the control level of a single factor equals the average for the other treatments, and where all non-control levels are equal, can both be expressed in terms of constraints.</page>
<page dir='en/contrasts' filePrefix='contrasts4'>The treatment sum of squares for an experiment with a control level can be split into a sum of squares explained by the difference between the control and other levels, and a sum of squares explained by differences between the non-control levels. This allows both constraints to be tested.</page>
<page dir='en/contrasts' filePrefix='contrasts5'>The treatment sum of squares can be split into components for differences between two groups of treatments, and for differences between these groups.</page>
<page dir='en/contrasts' filePrefix='contrasts6'>The above methods for splitting the treatment sum of squares can also be used in more complex experimental designs such as randomised blocks.</page>
<page dir='en/contrasts' filePrefix='contrasts7'>An alternative approach to analysing the structure of the levels of a factor estimates linear functions of the model parameter called contrasts.</page>

</section>

=== DougStirling/CAST/core/bk/massey130/xml/sec_leastSqrs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section SYSTEM "../../../structure/sectionXmlDefn.dtd">
<section name="Least squares">

<page dir="en/leastSqrs" filePrefix="leastSqrs_b1" summaryDir="en/leastSqrs" summaryFilePrefix="s_leastSqrs1" videoDir="en/leastSqrs" videoFilePrefix="v_leastSqrs_b1">A line or curve is useful for predicting the value of Y from a known value of X.</page>
<page dir="en/leastSqrs" filePrefix="leastSqrs2" summaryDir="en/leastSqrs" summaryFilePrefix="s_leastSqrs2" videoDir="en/leastSqrs" videoFilePrefix="v_leastSqrs2">A straight line can often be used to predict one variable from another.</page>
<page dir="en/leastSqrs" filePrefix="leastSqrs3" summaryDir="en/leastSqrs" summaryFilePrefix="s_leastSqrs3" videoDir="en/leastSqrs" videoFilePrefix="v_leastSqrs3">The difference between the actual value of Y and the value predicted by a line is called a residual. Small residuals are clearly desirable.</page>
<page dir="en/leastSqrs" filePrefix="leastSqrs4" summaryDir="en/leastSqrs" summaryFilePrefix="s_leastSqrs4" videoDir="en/leastSqrs" videoFilePrefix="v_leastSqrs4">The sum of squared residuals describes the accuracy of predictions from a line. The method of least squares positions the line to minimise the sum of squared residuals.</page>
<page dir="en/leastSqrs" filePrefix="leastSqrs5" summaryDir="en/leastSqrs" summaryFilePrefix="s_leastSqrs5" videoDir="en/leastSqrs" videoFilePrefix="v_leastSqrs5">A linear model is not appropriate if there are either curvature or outliers in a scatterplot of the data. Outliers should be carefully examined.</page>
<page dir="en/leastSqrs" filePrefix="leastSqrs6" summaryDir="en/leastSqrs" summaryFilePrefix="s_leastSqrs6" videoDir="en/leastSqrs" videoFilePrefix="v_leastSqrs6">Outliers and curvature in the relationship are often displayed more clearly in a plot of residuals.</page>
<page dir="en/leastSqrs" filePrefix="leastSqrs7" nameOverride="Predicting Y &amp; predicting X" note="Optional (not examined)#(opt)" summaryDir="en/leastSqrs" summaryFilePrefix="s_leastSqrs7" videoDir="en/leastSqrs" videoFilePrefix="v_leastSqrs7">Least squares does not treat Y and X symmetrically. The best line for predicting Y from X is different from the best line for predicting X from Y.</page>

</section>

=== DougStirling/CAST/core/bk/gaelic/xml/sec_randomPropn.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE section SYSTEM "../../../structure/sectionXmlDefn.dtd">

<section name='Distribution of sample proportion'>
<topText><![CDATA[
	<p>Categorical data sets are usually summarised by the proportions in the categories. For sample data, these proportions are random variables and have distributions.</p>
]]></topText>


<page dir='gd/randomPropn' filePrefix='randomPropn1'>The population proportion in a category is called its probability. Proportions and probabilities can be obtained from categorical and numerical variables.</page>
<page dir='gd/randomPropn' filePrefix='randomPropn2'>The sample proportion is a statistic that varies from sample to sample. The sample count in a category is also random with a discrete distribution.</page>
<page dir='gd/randomPropn' filePrefix='randomPropn3'>The sample count in a category has a standard distribution called a binomial distribution with parameters n and &amp;pi;.</page>
<page dir='gd/randomPropn' filePrefix='randomPropn4'>The binomial distribution can be used to find probabilities relating to sample counts.</page>
<page dir='gd/randomPropn' filePrefix='randomPropn5'>When the sample size is large, the distribution of the sample count in a category becomes close to a normal distribution.</page>
<page dir='gd/randomPropn' filePrefix='randomPropn6'>When the sample size is large, a normal approximation to the binomial distribution can be used to find binomial probabilities.</page>

</section>

=== DougStirling/CAST/core/bk/french_b/xml/sec_correlation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section SYSTEM "../../../structure/sectionXmlDefn.dtd">
<section name="Corr&amp;eacute;lation">
<topText><![CDATA[<p>Cette section d&eacute;crit une synth&egrave;se num&eacute;rique de la force de la relation entre deux variables, X et Y.</p>]]></topText>


<page dir="fr/correlation" filePrefix="correlation_b1">Une description num&amp;eacute;rique de la force d'une relation ne doit pas &amp;ecirc;tre affect&amp;eacute; par changement d'&amp;eacute;chelle des variables.</page>
<page dir="fr/correlation" filePrefix="correlation2">Standardiser une variable donne z-scores qui ne d&amp;eacute;pendent pas sur les unit&amp;eacute;s de la variable d'origine. (Le coefficient de corr&amp;eacute;lation sera d&amp;eacute;finie en termes de z-scores pour X et Y.)</page>
<page dir="fr/correlation" filePrefix="correlation3">Le coefficient de corr&amp;eacute;lation r&amp;eacute;sume la force de la relation entre X et Y. Il est +1 o&amp;ugrave; les croix nuage sont sur une ligne droite avec une pente positive, -1 quand sur une ligne avec une pente n&amp;eacute;gative et nulle lorsque X et Y sont ind&amp;eacute;pendantes.</page>
<page dir="fr/correlation" filePrefix="correlation4">Vous devriez &amp;ecirc;tre capable d'estimer la valeur de r en regardant un nuage de points et d'imaginer un nuage de croix correspondant &amp;agrave; une valeur de r.</page>
<page dir="fr/correlation" filePrefix="correlation5">Le coefficient de corr&amp;eacute;lation est seulement une bonne mesure de la force d'une relation, si les points dans un nuage de points sont dispers&amp;eacute;s autour d'une ligne droite, pas une courbe.</page>
<page dir="fr/correlation" filePrefix="correlation6">Le coefficient de corr&amp;eacute;lation ne peut pas identifier la courbure, les valeurs aberrantes ou des clusters et peut &amp;ecirc;tre trompeuse si ces caract&amp;eacute;ristiques sont pr&amp;eacute;sentes. Un diagramme de dispersion doit toujours &amp;ecirc;tre examin&amp;eacute; aussi.</page>

</section>

=== DougStirling/CAST/core/bk/french/xml/sec_indep.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section SYSTEM "../../../structure/sectionXmlDefn.dtd">
<section name="Indépendence">
<topText><![CDATA[<p>Les relations entre les variables catégorielles peuvent être décrits dans des termes similaires à ceux-ci utilisé pour des variables numériques.</p>]]></topText>


<page dir="fr/indep" filePrefix="indep1">Deux variables catégorielles, X et Y, sont associés lorsque la distribution conditionnelle de Y sachant X = x est différent pour différentes valeurs de x. Connaissant la valeur de X vous dit donc quelque chose sur Y.</page>
<page dir="fr/indep" filePrefix="indep2">Lorsque la distribution conditionnelle de Y est le même pour toutes les valeurs de X, les variables sont appelées indépendant. Ce cas particulier est d'une importance pratique.</page>
<page dir="fr/indep" filePrefix="indep3">L'indépendance est une propriété de la population. Pour évaluer l'indépendance d'une table échantillon d'urgence, le nombre de cellules observées sont comparées à celles estimées à partir d'un modèle à l'indépendance.</page>
<page dir="fr/indep" filePrefix="indep4">La somme brute de différences au carré entre le nombre de cellules observés et estimés est pas une bonne statistique de test.</page>
<page dir="fr/indep" filePrefix="indep5"> La statistique de chi-carré est une somme modifiée de différences au carré qui a une distribution standard (une distribution chi-carré) quand il est l'indépendance.</page>
<page dir="fr/indep" filePrefix="indep6">La statistique du chi-carré peut être utilisé pour trouver une p-valeur pour l'indépendance de test. La p-valeur n'a interprétation et propriétés similaires à p-valeurs pour tous les autres tests d'hypothèses.</page>
<page dir="fr/indep" filePrefix="indep7">Le test du chi-carré est appliqué à quelques ensembles de données réelles. Lorsque les variables sont révélés être associés, la nature de la relation est décrite à partir d'une comparaison entre le nombre de cellules observées et estimées.</page>
<page dir="fr/indep" filePrefix="indep8">Le test du chi carré évalue l'indépendance de deux variables catégoriques. Il est également utilisé pour tester si une variable catégorique a la même répartition en plusieurs groupes.</page>

</section>

=== DougStirling/CAST/core/bk/biometric/xml/sec_designIntro.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section SYSTEM "../../../structure/sectionXmlDefn.dtd">
<section name="Principles of experimental design">

<page dir="en/designIntro" filePrefix="designIntro_b1" summaryDir="en/designIntro" summaryFilePrefix="s_designIntro1" videoDir="en/designIntro" videoFilePrefix="v_designIntro_b1">Experiments are conducted to assess the effect of some categorical or numerical explanatory variable on a response. Experiments are characterised by the fact that the researcher can control the values of the explanatory variable that are used.</page>
<page dir="en/designIntro" filePrefix="designIntro2" summaryDir="en/designIntro" summaryFilePrefix="s_designIntro2" videoDir="en/designIntro" videoFilePrefix="v_designIntro2">In many experiments, the units on which the experiment is conducted are not identical. The varying characteristics of the experimental units may affect the response.</page>
<page dir="en/designIntro" filePrefix="designIntro3" summaryDir="en/designIntro" summaryFilePrefix="s_designIntro3" videoDir="en/designIntro" videoFilePrefix="v_designIntro3">If the treatments are badly allocated to experimental units, the experiment may over- or under-estimate their effect.</page>
<page dir="en/designIntro" filePrefix="designIntro4" summaryDir="en/designIntro" summaryFilePrefix="s_designIntro4" videoDir="en/designIntro" videoFilePrefix="v_designIntro4">If the experimental units that are chosen to get one treatment also differ in other ways, it will be impossible to tell whether it is the treatment or the other distinct characteristics of the units that affects the response.</page>
<page dir="en/designIntro" filePrefix="designIntro_b5" summaryDir="en/designIntro" summaryFilePrefix="s_designIntro5" videoDir="en/designIntro" videoFilePrefix="v_designIntro_b5">Random allocation of treatments to experimental units avoids systematic over- or under-estimation of treatment effects.</page>
<page dir="en/designIntro" filePrefix="designIntro6" summaryDir="en/designIntro" summaryFilePrefix="s_designIntro6" videoDir="en/designIntro" videoFilePrefix="v_designIntro6">If each treatment is used in more than one experimental unit, unit-to-unit variability can be assessed. This gives information about whether differences between the treatments are more than chance differences.</page>
<page dir="en/designIntro" filePrefix="designIntro7" summaryDir="en/designIntro" summaryFilePrefix="s_designIntro7" videoDir="en/designIntro" videoFilePrefix="v_designIntro7">By grouping similar experimental units into blocks and randomly allocating treatments within blocks, the treatment effects can be estimated more accurately.</page>

</section>

=== DougStirling/CAST/core/bk/german_b/xml/sec_estIntro.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section SYSTEM "../../../structure/sectionXmlDefn.dtd">
<section name="Einführung in statistische Schätzverfahren">

<page dir="de/estIntro" filePrefix="estIntro_b1">Werden Daten erhoben, dann sind wir normalerweise an der unbekannten Grundgesamtheit interessiert, aus der die Daten erhoben wurden.</page>
<page dir="de/estIntro" filePrefix="estIntro_b2">Mit einigen wenigen zusammenfassenden Maßzahlen (Parametern) zur Verteilung der Grundgesamtheit können oft die wichtigsten Eigenschaften beschrieben werden. Die entsprechenden Maßzahlen der Stichprobe (Statistiken) dienen uns dafür als Schätzungen.</page>
<page dir="de/estIntro" filePrefix="estIntro3">Auf dieser Seite werden einige Beispiel gezeigt, bei den Stichprobenstatistiken zur Schätzung wichtiger Populationsparameter genutzt werden.</page>
<page dir="de/estIntro" filePrefix="estIntro4">Der Unterschied zwischen einem Parameter der Grundgesamtheit und einer Stichprobenstatistik wird als Stichprobenfehler bezeichnet.</page>
<page dir="de/estIntro" filePrefix="estIntro_b5">Stichprobenfehler variieren von Stichprobe zu Stichprobe und folgen einer Verteilung.</page>
<page dir="de/estIntro" filePrefix="estIntro6">Ein guter Schätzer hat einen Fehler, der nah an Null liegt. Im besten Fall ist die Fehlerverteilung auf Null zentriert (kein Bias) und hat eine kleine Standardabweichung (Standardfehler). Der Standardfehler ist die Standardabweichung sowohl des Schätzers, als auch des Stichprobenfehlers.</page>
<page dir="de/estIntro" filePrefix="estIntro7">Ein Intervallschätzer ist eine Spannbreite an Werten, bei der wir zuversichtlich sind, dass innerhalb deren Schranken der unbekannte Parameter der Grundgesamtheit liegt.</page>

</section>

=== DougStirling/CAST/core/bk/spanish_b/xml/sec_seMean.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE section SYSTEM "../../../structure/sectionXmlDefn.dtd">

<section name='Standard error of mean'>

<page dir='es/seMean' filePrefix='seMean_b1'>When using a sample mean to estimate a population mean, the errors have a distribution with mean zero. The standard deviation of the errors (standard error) is the standard deviation of the sample mean.</page>
<page dir='es/seMean' filePrefix='seMean_b2'>If the population standard deviation is known, the standard error can be evaluated.</page>
<page dir='es/seMean' filePrefix='seMean_b3'>The estimation error has about 95% probability of being within ± standard errors of zero and is almost certainly within ±3 standard errors.</page>
<page dir='es/seMean' filePrefix='seMean_b4'>In most practical applications, the population standard deviation is unknown. The standard error of the sample mean can be approximated by replacing the population mean by the sample mean in its formula.</page>
<page dir='es/seMean' filePrefix='seMean5'>It is important to distinguish between the interpretation (and value) of the standard error (SE) and standard deviation (SD).</page>
<page dir='es/seMean' filePrefix='seMean_b6' note='(advanced)'>If there are two alternative estimators of a parameter, the estimator with lower standard error is usually better. The sample mean is shown to be a better estimator of the centre of a normal population than the sample median. </page>
<page dir='es/seMean' filePrefix='seMean7' note='(advanced)'>Unbiased estimators are usually preferred. The sample median is shown to be a biased estimator of the mean of a skew distribution.</page>

</section>
