=== DougStirling/CAST/core/structure/sectionXmlDefn.dtd
<!ATTLIST section name CDATA #REQUIRED>
<!ATTLIST section shortName CDATA #IMPLIED>
<!ELEMENT section (topText?, page*)>

<!ELEMENT topText (#PCDATA)>

<!ATTLIST page dir CDATA #REQUIRED>
<!ATTLIST page filePrefix CDATA #REQUIRED>
<!ATTLIST page summaryDir CDATA #IMPLIED>
<!ATTLIST page summaryFilePrefix CDATA #IMPLIED>
<!ATTLIST page videoDir CDATA #IMPLIED>
<!ATTLIST page videoFilePrefix CDATA #IMPLIED>
<!ATTLIST page note CDATA #IMPLIED>				<!-- Comment after page name in section list -->
<!ATTLIST page nameOverride CDATA #IMPLIED>		<!-- Overrides page name -->
<!ELEMENT page (#PCDATA)>

=== DougStirling/CAST/core/bk/french/xml/sec_multiGroup.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section SYSTEM "../../../structure/sectionXmlDefn.dtd">
<section name="En comparant plusieurs moyensmeans">


<page dir="fr/multiGroup" filePrefix="multiGroup1">Pour comparer les moyens de plusieurs groupes, un modèle de distributions normales dans tous les groupes est utilisé, mais tous les écarts-types de groupe doit être supposé être le même.</page>
<page dir="fr/multiGroup" filePrefix="multiGroup2">Les écarts-types de l'échantillon dans les groupes distincts peuvent être combinés pour donner une estimation globale de l'écart-type commun, σ.</page>
<page dir="fr/multiGroup" filePrefix="multiGroup3" note="(optional)">Intervalles de confiance et des tests d'hypothèses antérieures pour l'égalité des deux moyens de groupe peuvent être améliorées lorsque les écarts-types de groupe sont connus pour être les mêmes. Cependant ce raffinement est pas recommandé pour une utilisation générale.</page>
<page dir="fr/multiGroup" filePrefix="multiGroup4">La variabilité entre les moyennes de groupe et de la variabilité au sein des groupes doit être utilisé pour évaluer si les groupes diffèrent.</page>
<page dir="fr/multiGroup" filePrefix="multiGroup5">La variabilité au sein des groupes et entre les groupes sont décrits par des sommes de carrés.</page>
<page dir="fr/multiGroup" filePrefix="multiGroup6">Le coefficient de détermination (R²) est le rapport entre les groupes et les sommes totales des carrés. Il est de la proportion de variation qui peut être expliqué par des différences entre les groupes.</page>
<page dir="fr/multiGroup" filePrefix="multiGroup7">Le F-ratio est une statistique de test qui est basé sur l'inter- et intra-groupes des sommes de carrés. Les tests p-valeur associées si tous les groupes ont la même moyenne.</page>
<page dir="fr/multiGroup" filePrefix="multiGroup8">Le test F est appliqué à un petit nombre d'ensembles de données.</page>

</section>

=== DougStirling/CAST/core/bk/smsbiom/xml/sec_Exercise3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section SYSTEM "../../../structure/sectionXmlDefn.dtd">
<section name="Exercises">


<page dir="en/normalDistn" filePrefix="e_normalDistn1">One exercise asks you to guess the standard deviation of a normal distribution. Another requests a sketch of a normal distribution given its mean and standard deviation.</page>





<page dir="en/normalDistn" filePrefix="e_normalDistn7">The 70-95-100 rule of thumb gives the approximate probability of a value within 1, 2 and 3 standard deviations of the mean. Te exercise uses this rule of thumb to find some normal probabilities without formal calculations.</page>

<page dir="en/popSamp" filePrefix="e_popSamp1">The exercise on this page asks whether three statements describe populations or samples.</page>
<page dir="en/popSamp" filePrefix="e_popSamp2">This exercise asks whether three statements describe parameters or estimates.</page>
<page dir="en/seMean" filePrefix="e_seMean1">The exercise on this page shows a data set with the sample mean and st devn. The standard error of the mean must be calculated.</page>
<page dir="en/seMean" filePrefix="e_seMean2">This exercise states the value of either the standard deviation or the standard error or the mean. The question asks for an interval containing about 95% of the values or an interval with 95% confidence of including the popn mean.</page>
<page dir="en/seMean" filePrefix="e_seMean3">This exercise asks 3 questions about the effect of sample size and spread of sample values on the sd and se, and about the interpretation of the se and sd.</page>
<page dir="en/ciMean" filePrefix="e_ciMean3">This exercise is similar to the previous one but requires use of a t distribution since the population standard deviation is unknown.</page>
<page dir="en/ciMean" filePrefix="e_ciMean6">This exercise asks how the sample size, sample standard deviation and confidence level affect the width of a CI for the mean.</page>
<page dir="en/ciMean" filePrefix="e_ciMean7">In this exercise, you must choose which of four statements correctly interprets the meaning of a 95% confidence interval.</page>
</section>

=== DougStirling/CAST/core/bk/german/xml/sec_testIntro.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE section SYSTEM "../../../structure/sectionXmlDefn.dtd">

<section name='Introduction to hypothesis tests'>

<page dir='de/testIntro' filePrefix='testIntro1'>Estimation asks which values for an unknown parameter are consistent with data that have been collected. Hypothesis testing usually asks whether the data are consistent with some parameter values.</page>
<page dir='de/testIntro' filePrefix='testIntro2'>Are some teams in a soccer league better than others, or is the end-of-season league table consistent with random results from equally-matched teams? A simulation can help to answer this question.</page>
<page dir='de/testIntro' filePrefix='testIntro3'>This page presents a simulation to test whether the number of observations observed in one category is consistent with a specified probability.</page>
<page dir='de/testIntro' filePrefix='testIntro4'>This page uses a simulation to test whether a sample is consistent with a particular population mean.</page>
<page dir='de/testIntro' filePrefix='testIntro5' note='(optional)'>A method is presented to assess whether the population means in two groups are the same.</page>
<page dir='de/testIntro' filePrefix='testIntro6' note='(advanced)'>The correlation between teams' final points in two successive seasons will be relatively high if some teams are better than others. Randomising points in the second season gives an indication of whether the actual correlation is unusually high.</page>
<page dir='de/testIntro' filePrefix='testIntro7'>All hypothesis tests involve a null hypothesis, a summary statistic for testing, an alternative hypothesis and a p-value.</page>

</section>

=== DougStirling/CAST/core/bk/fr_esiac/xml/sec_boxPlot.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section SYSTEM "../../../structure/sectionXmlDefn.dtd">
<section name="Médiane, quartiles et boîtes à moustaches">
<topText><![CDATA[
	<p>Box parcelles très résument la distribution des valeurs dans un ensemble de données. Ils sont utiles pour comparer différents lots de valeurs.</p>
]]></topText>


<page dir="fr/boxPlot" filePrefix="boxPlot1" summaryDir="en/boxPlot" summaryFilePrefix="s_boxPlot1" videoDir="en/boxPlot" videoFilePrefix="v_boxPlot1">Dot parcelles, la tige et les parcelles des feuilles et des histogrammes contiennent des informations détaillées qui est distrait lorsque deux ou plusieurs ensembles de données sont comparées.</page>
<page dir="fr/boxPlot" filePrefix="boxPlot2" summaryDir="en/boxPlot" summaryFilePrefix="s_boxPlot2" videoDir="en/boxPlot" videoFilePrefix="v_boxPlot2">La médiane et les quartiles répartissent un lot de valeurs en quatre ensembles de taille égale de valeurs. Une boîte à moustaches est un affichage graphique de la médiane, quartiles et extrêmes.</page>
<page dir="fr/boxPlot" filePrefix="boxPlot3" summaryDir="en/boxPlot" summaryFilePrefix="s_boxPlot3" videoDir="en/boxPlot" videoFilePrefix="v_boxPlot3">Une boîte à moustaches montre clairement le centre, la propagation et l'asymétrie d'un ensemble de données. Il divise l'histogramme correspondant en 4 zones approximativement égales.</page>
<page dir="fr/boxPlot" filePrefix="boxPlot4" summaryDir="en/boxPlot" summaryFilePrefix="s_boxPlot4" videoDir="en/boxPlot" videoFilePrefix="v_boxPlot4">L'intrigue de la boîte de base est souvent modifié pour afficher les valeurs aberrantes que des croix séparés.</page>
<page dir="fr/boxPlot" filePrefix="boxPlot5" summaryDir="en/boxPlot" summaryFilePrefix="s_boxPlot5" videoDir="en/boxPlot" videoFilePrefix="v_boxPlot5">Box parcelles ne peuvent pas montrer des grappes, de sorte ne doivent jamais être utilisé pour les données avec des clusters.</page>
<page dir="fr/boxPlot" filePrefix="boxPlot6" summaryDir="en/boxPlot" summaryFilePrefix="s_boxPlot6" videoDir="en/boxPlot" videoFilePrefix="v_boxPlot6">Box parcelles sont particulièrement efficaces pour l'affichage des différences entre plusieurs groupes de valeurs.</page>

</section>

=== DougStirling/CAST/core/bk/agExper/xml/sec_oneBlockAnova.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE section SYSTEM "../../../structure/sectionXmlDefn.dtd">

<section name='Anova for randomised blocks'>


<page dir='en/oneBlockAnova' filePrefix='oneBlockAnova1'>The simplest model for a single factor in a randomised block design is very similar to the model without interaction for designs with two factors.</page>
<page dir='en/oneBlockAnova' filePrefix='oneBlockAnova2'>Adding terms to the model for blocks and for the factor reduce the residual sum of squares. Each reduction is the sum of squared differences between the fitted values from two models.</page>
<page dir='en/oneBlockAnova' filePrefix='oneBlockAnova3'>The explained sums of squares for blocks is the sums of squared differences between the block means and overall mean. The treatment sum of squares is similarly the sum of squared differences between the treatment and overall means.</page>
<page dir='en/oneBlockAnova' filePrefix='oneBlockAnova4'>Adding a term for blocks to the model can be thought of as adjusting the values to make all block means equal. The residuals from the full model can be thought of as a further adjustment to make all treatment means equal.</page>
<page dir='en/oneBlockAnova' filePrefix='oneBlockAnova5'>An anova table shows these sums of squares and associated degrees of freedom. The F-ratio for treatments in the table is the basis of a test for equal treatment means. Several examples are given.</page>
<page dir='en/oneBlockAnova' filePrefix='oneBlockAnova6'>The anova table test for equal treatment means is based on a model that makes assumptions about the data. When the unexplained response variation is not constant, a transformation of the response may fit the model better.</page>
<page dir='en/oneBlockAnova' filePrefix='oneBlockAnova7'>If it is concluded that all treatment means are not equal, confidence intervals can be used to report the differences.</page>

</section>

=== DougStirling/CAST/core/bk/french/xml/sec_ciMean.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section SYSTEM "../../../structure/sectionXmlDefn.dtd">
<section name="Intervalle de confiance pour la moyenne">

<page dir="fr/ciMean" filePrefix="ciMean1">L'erreur d'estimation pour tout estimateur sans biais, a environ 0,95 probabilité d'être entre -2SE et + 2SE. Un intervalle de confiance approximatif de 95% pour le paramètre est donc l'estimation ± 2SE.</page>
<page dir="fr/ciMean" filePrefix="ciMean2">Si l'écart type de population est connue, l'erreur-type peut être déterminée précisément. Un intervalle de confiance de 95% est la moyenne de l'échantillon deux fois cette ±. (Ou plus exactement, 1,96 fois l'erreur-type.)</page>
<page dir="fr/ciMean" filePrefix="ciMean3">Une simulation montre que les intervalles de confiance à 95% sont aléatoires - elles varient d'un échantillon à. Environ 95% des échantillons donne des intervalles de confiance qui comprennent le véritable paramètre.</page>
<page dir="fr/ciMean" filePrefix="ciMean4">Dans la pratique, l'écart type de population est généralement inconnue. Si la population SD est simplement remplacée par son équivalent d'échantillon, l'estimation d'intervalle a un niveau de confiance inférieur à 95%.</page>
<page dir="fr/ciMean" filePrefix="ciMean5">Pour obtenir un niveau de confiance de 95%, une valeur t à partir de tables doit remplacer la constante 1,96.</page>
<page dir="fr/ciMean" filePrefix="ciMean6">Une simulation montre que les intervalles de 95% de confiance qui en résultent ont une probabilité de 0,95 d'inclure la moyenne de la population.</page>
<page dir="fr/ciMean" filePrefix="ciMean7">Quelques exemples des intervalles de confiance de 95% pour les moyens de population sont donnés et interprétés.</page>

</section>

=== DougStirling/CAST/core/bk/massey130/xml/sec_regnEst.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section SYSTEM "../../../structure/sectionXmlDefn.dtd">
<section name="Estimating parameters">


<page dir="en/regnEst" filePrefix="regnEst1" summaryDir="en/regnEst" summaryFilePrefix="s_regnEst1" videoDir="en/regnEst" videoFilePrefix="v_regnEst1">A least squares line provides estimates of the linear model's slope and intercept. These estimates are random values &amp;mdash; they vary from sample to sample.</page>
<page dir="en/regnEst" filePrefix="regnEst2" summaryDir="en/regnEst" summaryFilePrefix="s_regnEst2" videoDir="en/regnEst" videoFilePrefix="v_regnEst2">The third parameter of the normal linear model is the error standard deviation. It can be estimated using the residuals from the least squares line.</page>
<page dir="en/regnEst" filePrefix="regnEst3" summaryDir="en/regnEst" summaryFilePrefix="s_regnEst3" videoDir="en/regnEst" videoFilePrefix="v_regnEst3">The least squares estimate of the model's slope has a normal distribution that is centred on the true value.</page>
<page dir="en/regnEst" filePrefix="regnEst4" summaryDir="en/regnEst" summaryFilePrefix="s_regnEst4" videoDir="en/regnEst" videoFilePrefix="v_regnEst4">The distribution of the least squares slope may be estimated from a single data set.</page>
<page dir="en/regnEst" filePrefix="regnEst5" summaryDir="en/regnEst" summaryFilePrefix="s_regnEst5" videoDir="en/regnEst" videoFilePrefix="v_regnEst5">A confidence interval for the model's slope can be obtained from its least squares estimate and its standard error.</page>
<page dir="en/regnEst" filePrefix="regnEst6" summaryDir="en/regnEst" summaryFilePrefix="s_regnEst6" videoDir="en/regnEst" videoFilePrefix="v_regnEst6">Confidence intervals for the model's slope have the same properties as confidence intervals for population means or proportions.</page>
<page dir="en/regnEst" filePrefix="regnEst7" nameOverride="Influences on accuracy" note="Optional (not examined)#(opt)" summaryDir="en/regnEst" summaryFilePrefix="s_regnEst7" videoDir="en/regnEst" videoFilePrefix="v_regnEst7">The standard error of the least squares slope depends on the response standard deviation round the model line, the sample size and the standard deviation of X. Collecting data with a big spread of x-values gives more accurate estimates but there are disadvantages.</page>

</section>

=== DougStirling/CAST/core/bk/generalx/xml/sec_probDensity.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE section SYSTEM "../../../structure/sectionXmlDefn.dtd">

<section name='Probability &amp;amp; probability density'>

<page dir='en/probDensity' filePrefix='l_probDensity1'>This diagram shows a bar chart of a finite categorical population. Clicking any bar labels it with the probability that a single sampled value is that category -- i.e. the bar height.</page>
<page dir='en/probDensity' filePrefix='l_probDensity2'>This diagram illustrates that the population proportion of values in a range equals the probability for a single value. A range of values on the population dot plot can be highlighted and is labeled both as a proportion and probability.</page>
<page dir='en/probDensity' filePrefix='l_probDensity3'>In this diagram, the sample size can be increased, showing that a sample proportion tends to a limit (the probability) as the sample size increases.</page>
<page dir='en/probDensity' filePrefix='l_probDensity4'>This simulation shows how a bar chart becomes more stable when the sample size increases. The limiting bar chart gives the population probabilities.</page>
<page dir='en/probDensity' filePrefix='l_probDensity5'>A simulation shows how a histogram becomes more stable and smoother when the sample size increases and classes are made narrower. The limiting histogram is called a probability density function.</page>
<page dir='en/probDensity' filePrefix='l_probDensity6'>This diagram show a normal pdf with sliders to adjust the mean and sd. (The area remains constant.)</page>
<page dir='en/probDensity' filePrefix='l_probDensity7'>This diagram shows the histogram of a real data set for which a normal distribution is a reasonable model. The parameters of the superimposed normal pdf can be adjusted to match the histogram shape.</page>
<page dir='en/probDensity' filePrefix='l_probDensity8'>This diagram allows you to drag over the classes in a histogram or the possible values in a pdf. It illustrates that area equals probability.</page>

</section>
