=== DougStirling/CAST/core/structure/sectionXmlDefn.dtd
<!ATTLIST section name CDATA #REQUIRED>
<!ATTLIST section shortName CDATA #IMPLIED>
<!ELEMENT section (topText?, page*)>

<!ELEMENT topText (#PCDATA)>

<!ATTLIST page dir CDATA #REQUIRED>
<!ATTLIST page filePrefix CDATA #REQUIRED>
<!ATTLIST page summaryDir CDATA #IMPLIED>
<!ATTLIST page summaryFilePrefix CDATA #IMPLIED>
<!ATTLIST page videoDir CDATA #IMPLIED>
<!ATTLIST page videoFilePrefix CDATA #IMPLIED>
<!ATTLIST page note CDATA #IMPLIED>				<!-- Comment after page name in section list -->
<!ATTLIST page nameOverride CDATA #IMPLIED>		<!-- Overrides page name -->
<!ELEMENT page (#PCDATA)>

=== DougStirling/CAST/core/bk/smsbiom/xml/sec_centerSpread.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section SYSTEM "../../../structure/sectionXmlDefn.dtd">
<section name="Describing centre and spread">


<page dir="en/centerSpread" filePrefix="centerSpread_b2" summaryDir="en/centerSpread" summaryFilePrefix="s_centerSpread2" videoDir="en/centerSpread" videoFilePrefix="v_centerSpread_b2">The median is a summary of the centre of a distribution. The range and inter-quartile range both describe spread.</page>
<page dir="en/centerSpread" filePrefix="centerSpread_b3" summaryDir="en/centerSpread" summaryFilePrefix="s_centerSpread3" videoDir="en/centerSpread" videoFilePrefix="v_centerSpread_b3">The median and mean are alternative measures of the centre of a distribution.</page>
<page dir="en/centerSpread" filePrefix="centerSpread4" summaryDir="en/centerSpread" summaryFilePrefix="s_centerSpread4" videoDir="en/centerSpread" videoFilePrefix="v_centerSpread4">When a data set is not symmetric, the mean and median may differ substantially.</page>
<page dir="en/centerSpread" filePrefix="centerSpread5" summaryDir="en/centerSpread" summaryFilePrefix="s_centerSpread5" videoDir="en/centerSpread" videoFilePrefix="v_centerSpread5">The standard deviation is the most commonly used numerical summary of the spread of values in a data set.</page>
<page dir="en/centerSpread" filePrefix="centerSpread6" summaryDir="en/centerSpread" summaryFilePrefix="s_centerSpread6" videoDir="en/centerSpread" videoFilePrefix="v_centerSpread6">The 70-95-100 rule-of-thumb is useful for understanding the numerical value of the standard deviation.</page>

<page dir="en/centerSpread" filePrefix="centerSpread8" summaryDir="en/centerSpread" summaryFilePrefix="s_centerSpread8" videoDir="en/centerSpread" videoFilePrefix="v_centerSpread8">The mean and standard deviation cannot give any indication of the existance of outliers, skewness or clusters. A dot plot or histogram should be examined before reporting these numerical summaries.</page>

<page dir="en/moreVariation" filePrefix="moreVariation1" summaryDir="en/moreVariation" summaryFilePrefix="s_moreVariation1" videoDir="en/moreVariation" videoFilePrefix="v_moreVariation1">If a data set contains an outlier, the mean and especially the standard deviation can be badly affected. The values may be obviously wrong when the 70-95-100 rule is applied in the context of the data but examining a dot plot or box plot is best.</page>
</section>

=== DougStirling/CAST/core/bk/ncea/xml/sec_densityMore.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section SYSTEM "../../../structure/sectionXmlDefn.dtd">
<section name="More about histograms">
<topText><![CDATA[
	<p>Many teachers at NCEA level 1 only cover histograms in which all classes have equal widths and class height can therefore be equal to frequency. Some teachers explain how to draw histograms with unequal class widths to their better students. All students should however understand the relationship between the proportion of values in the histogram classes and histogram area.</p>
]]></topText>


<page dir="en/density" filePrefix="density5" summaryDir="en/density" summaryFilePrefix="s_density5" videoDir="en/density" videoFilePrefix="v_density5">In a histogram, the proportion of the total area that is above any class equals the relative frequency of the class.</page>
<page dir="en/density" filePrefix="density7" note="Advanced" summaryDir="en/density" summaryFilePrefix="s_density7" videoDir="en/density" videoFilePrefix="v_density7">If a histogram has varying class widths, the vertical axis must be 'density'. The histogram shape would be misleading if frequency or relative frequency was used for the vertical axis.</page>
<page dir="en/density" filePrefix="density8" summaryDir="en/density" summaryFilePrefix="s_density8" videoDir="en/density" videoFilePrefix="v_density8">Whether or not class widths are equal, the proportion of values in any classes always equals the proportion of the total histogram area that is above the classes.</page>

<page dir="bk/ncea" filePrefix="e_densityMore1" nameOverride="#r#Exercise: #+#Draw histogram with mixed class widths">In this page, you will draw histograms of different data sets.</page>
<page dir="en/density" filePrefix="e_density2" nameOverride="#r#Exercise: #+#Histogram areas and proportions">The two exercises in this page ask you to use the shape of a histogram to find the proportion of values in a given range. The first exercise shows the number of values in each class, but the second requires the histogram area to be estimated 'by eye'.</page>

</section>

=== DougStirling/CAST/core/bk/german_b/xml/sec_randomPropn.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section SYSTEM "../../../structure/sectionXmlDefn.dtd">
<section name="Stichprobenverteilung von Häufigkeiten">
<topText><![CDATA[<p>Kategorielle Daten werden gewöhnlich durch Häufigkeiten zusammengefasst. Bei Stichproben sind diese Häufigkeiten Zufallsvariablen und unterliegen Wahrscheinlichkeitsverteilungen.</p>]]></topText>


<page dir="de/randomPropn" filePrefix="randomPropn1">Die Häufigkeit einer Kategorie in der Grundgesamtheit beschreibt ihre Wahrscheinlichkeit. Häufigkeiten und Wahrscheinlichkeiten können sowohl für metrische, als auch für kategorielle Variablen abgeleitet werden.</page>
<page dir="de/randomPropn" filePrefix="randomPropn2">Die Häufigkeit einer Kategorie in einer Stichprobe ist eine Statistik, die von Stichprobe zu Stichprobe schwanken kann. Die absolute Häufigkeit einer Kategorie in einer Stichprobe ist, genau wie die relative Häufigkeit, eine Zufallsvariable. Die absolute Häufigkeit folgt dabei einer diskreten Häufigkeitsverteilung.</page>
<page dir="de/randomPropn" filePrefix="randomPropn_b3">Die absolute Häufigkeit einer Kategorie in einer Stichprobe folgt gewöhlich einer Binomialverteilung mit den Parametern n und p.</page>
<page dir="de/randomPropn" filePrefix="randomPropn_b4">Die Binomialverteilung kann verwendet werden um Wahrscheinlichkeiten für absolute Häufigkeiten in einer Stichprobe zu ermitteln.</page>
<page dir="de/randomPropn" filePrefix="randomPropn5">Ist der Stichprobenumfang groß, dann nähert sich die Binomialverteilung der Normalverteilung an.</page>
<page dir="de/randomPropn" filePrefix="randomPropn_b6">Ist der Stichprobenumfang groß, dann kann die Normalverteilung verwendet werden, um binomiale Wahrscheinlichkieten zu ermitteln.</page>

</section>

=== DougStirling/CAST/core/bk/french_b/xml/sec_designTwo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section SYSTEM "../../../structure/sectionXmlDefn.dtd">
<section name="Two or more factors">

<page dir="fr/designTwo" filePrefix="designTwo_b1">A second factor can be varied in a randomised experiment for one factor without affecting the accuracy of the estimated effect of the first factor.</page>
<page dir="fr/designTwo" filePrefix="designTwo_b2">In a factorial experiment, each combination of the levels of two or more factors is used on the same number of experimental units.</page>
<page dir="fr/designTwo" filePrefix="designTwo3">The simplest model for the effect of two factors assumes that the effect of each factor is the same, whatever the value of the other factor. The mean response can be written as the sum of the effects of the separate factors.</page>
<page dir="fr/designTwo" filePrefix="designTwo4">If the effect of one factor depends on the level of the other, there is said to be interaction between them. Interaction can be assessed from a factorial experiment.</page>
<page dir="fr/designTwo" filePrefix="designTwo5">This example helps to explain the concept of interaction.</page>
<page dir="fr/designTwo" filePrefix="designTwo_b6">The simplest model for three or more factors assumes that the effect of each does not depend on the levels of the others. The mean response is modelled as the sum of terms for the individual factors.</page>
<page dir="fr/designTwo" filePrefix="designTwo7">In factorial experiments with 3 or more factors, there may be interactions between two or more of the factors.</page>

</section>

=== DougStirling/CAST/core/bk/german/xml/sec_centerSpread.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section SYSTEM "../../../structure/sectionXmlDefn.dtd">
<section name="Lage und Streuung beschreiben">

<page dir="de/centerSpread" filePrefix="centerSpread1">Das Zentrum einer Verteilung ist ein 'typischer Wert'. Die Streuung beschreibt, wie stark die Werte um das Zentrum streuen.</page>
<page dir="de/centerSpread" filePrefix="centerSpread2">Der Median ist ein Lagemaß. Variationsbreite und Interquartilsbreite sind Streuungsmaße.</page>
<page dir="de/centerSpread" filePrefix="centerSpread3">Der Median und das arithmetische Mittel sind beide Lagemaße.</page>
<page dir="de/centerSpread" filePrefix="centerSpread4">Sind Datensätze unsymmetrisch können sich der Median und das arithmetische Mittel deutlich unterscheiden.</page>
<page dir="de/centerSpread" filePrefix="centerSpread5">Die Streuung wird am häufigsten durch die Standardabweichung ausgedrückt.</page>
<page dir="de/centerSpread" filePrefix="centerSpread6">Die 70-95-100 Faustregel ist nützlich um die Standardabweichung interpretieren zu können.</page>
<page dir="de/centerSpread" filePrefix="centerSpread7">Aus einem Histogramm kann man grob das arithmetische Mittel und die Standardabweichung schätzen. </page>
<page dir="de/centerSpread" filePrefix="centerSpread8">Ein Dotplot oder Histogramm sollte erstellt werden, um Ausreisser, Schiefe und Cluster zu erkennen, da Standardabweichung und Mittelwert darüber keine Aussagen zulassen.</page>

</section>

=== DougStirling/CAST/core/bk/massey200/xml/sec_fixedSigLevel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section SYSTEM "../../../structure/sectionXmlDefn.dtd">
<section name="Fixed significance level">
<topText><![CDATA[<p>This section will not be examined. Hypothesis tests are usually conducted by interpreting p-values. However test results are sometimes reported as accepting or rejecting the null hypothesis at fixed significance levels and this section examines consequences of that approach.</p>]]></topText>

<page dir="en/fixedSigLevel" filePrefix="fixedSigLevel1" summaryDir="en/fixedSigLevel" summaryFilePrefix="s_fixedSigLevel1" videoDir="en/fixedSigLevel" videoFilePrefix="v_fixedSigLevel1">Hypothesis tests are often based on interpreting a p-value. An alternative approach involves a decision that is made about which of the two hypotheses is true. The significance level is the probability of wrongly concluding that the null hypothesis is not true.</page>
<page dir="en/fixedSigLevel" filePrefix="fixedSigLevel2" note="Optional (not examined)#(Opt)" summaryDir="en/fixedSigLevel" summaryFilePrefix="s_fixedSigLevel2">Two types of error can be made from a test; deciding that H₀ is true when it is false, and deciding it is false when it is true.</page>
<page dir="en/fixedSigLevel" filePrefix="fixedSigLevel3" note="Optional (not examined)#(Opt)" summaryDir="en/fixedSigLevel" summaryFilePrefix="s_fixedSigLevel3">A test with significance level α can be based on the test's p-value. The null hypothesis is rejected if the p-value is less than α.</page>
<page dir="en/fixedSigLevel" filePrefix="fixedSigLevel4" note="Optional (not examined)#(Opt)" summaryDir="en/fixedSigLevel" summaryFilePrefix="s_fixedSigLevel4">For discrete data, it is usually impossible to find a decision rule with significance level exactly 5% (or any other pre-specified value). A conservative test uses a significance level that is just under the required value.</page>
<page dir="en/fixedSigLevel" filePrefix="fixedSigLevel5" note="Optional (not examined)#(Opt)" summaryDir="en/fixedSigLevel" summaryFilePrefix="s_fixedSigLevel5">The power of a test is the probability of accepting H₀ when it is false. Since this usually depends on the actual parameter value, it is a function that can be graphed.</page>
<page dir="en/fixedSigLevel" filePrefix="fixedSigLevel6" note="Optional (not examined)#(Opt)" summaryDir="en/fixedSigLevel" summaryFilePrefix="s_fixedSigLevel6">If a hypothesis test's significance level and its power at some value of the parameter are specified, the sample size can be determined to achieve this.</page>
</section>

=== DougStirling/CAST/core/bk/german_b/xml/sec_sampPractice.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section SYSTEM "../../../structure/sectionXmlDefn.dtd">
<section name="Stichproben in der Praxis">
<topText><![CDATA[<p>In vielen praxisnahen Situationen gibt es bessere Methoden der Stichprobenerhebung, als die einfache zufällige Stichprobenziehung. Welche Methode man auch immer verwendet: Fehler, die nicht auf zufällige Schwankungen zurückzuführen sind, können einen extrem negativen Effekt auf das Ergebnis haben.</p>]]></topText>


<page dir="de/sampPractice" filePrefix="sampPractice_b1">Teilweise lassen sich bessere Schätzungen ermitteln, wenn die Zufallsstichproben innerhalb verschiedener Gruppen der Grundgesamtheit erhoben werden.</page>
<page dir="de/sampPractice" filePrefix="sampPractice2">Sind die Versuchseinheiten in sogenannten Klumpen (englisch Clusters) angeordnet, ist es häufig günstiger die Klumpen komplett zu untersuchen. Die zufällige Auswahl bezieht sich dann darauf, welche Klumpen aus der Grundgesamtheit zufällig gewählt werden.</page>
<page dir="de/sampPractice" filePrefix="sampPractice3">Ist die zu untersuchende Grundgesamtheit über ein weites Gebiet verteilt, dann kann es Sinn machen nur Stichproben in einigen Teilregionen zu erheben.</page>
<page dir="de/sampPractice" filePrefix="sampPractice4">Stichproben werden normalerweise erhoben, um bestimmte Charakteristiken einer Grundgesamtheit zu schätzen. Die Variation, die aus der Stichprobenziehung resultiert wird Stichprobenfehler genannt. Schwierigkeiten in der praktischen Umsetzung der Stichprobenerhebung können zu verzerrten Schätzungen führen (Bias).</page>
<page dir="de/sampPractice" filePrefix="sampPractice_b5">Bestimmte Arten von Fehlern bewirken, dass bestimmte Versuchobjekte nicht in die Stichprobe gelangen können.</page>
<page dir="de/sampPractice" filePrefix="sampPractice_b6">Interviewer-Fehler und Messfehler können zu falschen Messungen führen.</page>
<page dir="de/sampPractice" filePrefix="sampPractice7">Zum Design von Fragebögen gibt es eine Vielzahl von Mechanismen und Methoden. Alle haben jeweils ganz bestimmte Vor- und Nachteile.</page>

</section>

=== DougStirling/CAST/core/bk/spanish_b/xml/sec_centerSpread.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section SYSTEM "../../../structure/sectionXmlDefn.dtd">
<section name="Descripción del centro y de la extensión">

<page dir="es/centerSpread" filePrefix="centerSpread_b1">El centro de una distribución es un &#8220;valor típico&#8221;. La extensión describe hasta dónde los valores son del centro.</page>
<page dir="es/centerSpread" filePrefix="centerSpread_b2">El punto medio es un resumen del centro de una distribución. La gama y la gama intercuartil ambas describen la extensión.</page>
<page dir="es/centerSpread" filePrefix="centerSpread_b3">El punto medio y el medio son medidas alternativas del centro de una distribución.</page>
<page dir="es/centerSpread" filePrefix="centerSpread4">Cuando un conjunto de datos no es simétrico, el malo y el punto medio pueden diferenciar substancialmente.</page>
<page dir="es/centerSpread" filePrefix="centerSpread5">La desviación estándar es el resumen numérico más de uso general de la extensión de valores en un conjunto de datos.</page>
<page dir="es/centerSpread" filePrefix="centerSpread6">La regla empírica 70-95-100 es útil para entender el valor numérico de la desviación estándar.</page>
<page dir="es/centerSpread" filePrefix="centerSpread7">Es posible conjeturar áspero la desviación mala y estándar de un histograma y bosquejar áspero un histograma simétrico que empareja cualquier desviación mala y estándar dada.</page>
<page dir="es/centerSpread" filePrefix="centerSpread8">La desviación mala y estándar no puede dar ninguna indicación de la existencia de afloramientos, de la oblicuidad o de racimos. Un diagrama o un histograma del punto debe ser examinado antes de divulgar estos resúmenes numéricos.</page>

</section>
